export const UPDATE_FOO = 'UPDATE_FOO'

export const ADD_ACTIONNUM = 'ADD_ACTIONNUM'

export const DELETE_ACTIONNUM = 'DELETE_ACTIONNUM'

export const INPUT_TOPAGE_PARAMS = 'INPUT_TOPAGE_PARAMS'

export const ADD_MSG_QUEUE = 'ADD_MSG_QUEUE'

export const SET_MSG_QUEQUE = 'SET_MSG_QUEQUE'

export const HAS_DIRECT_PAGE = 'HAS_DIRECT_PAGE'

export const DELETE_MSG_PROCESSED = 'DELETE_MSG_PROCESSED'

export const ADD_TO_ACCOUNT_LIST = 'ADD_ACCOUNT_LIST'

export const DEL_FROM_ACCOUNT_LIST = 'DEL_ACCOUNT_LIST'

export const CURRENT_ACCOUNT = 'CURRENT_ACCOUNTS'

export const ACCOUNT_LIST = 'ACCOUNT_LIST'
