export const UPDATE_FOO = 'UPDATE_FOO'

export const ADD_ACTIONNUM = 'ADD_ACTIONNUM'

export const DELETE_ACTIONNUM = 'DELETE_ACTIONNUM'

export const INPUT_TOPAGE_PARAMS = 'INPUT_TOPAGE_PARAMS'

export const ADD_MSG_QUEUE = 'ADD_MSG_QUEUE'

export const CLONE_STATE = 'CLONE_STATE'

export const HAS_DIRECT_PAGE = 'HAS_DIRECT_PAGE'

export const DELETE_MSG_PROCESSED = 'DELETE_MSG_PROCESSED'

export const SET_ACCOUNT = 'SET_ACCOUNT'
